### ISSUE TITLE
[Bug] i18n problem: Improper Font Display When Browser Language is Not Chinese or English (zh_CN/en_US)

### ISSUE THREAD

**Issue by Statrue** [nepsyn/minaplay#101]
### Is there a question you'd like to ask in an existing issue?

- [x] I've checked an existing issue and my current issue isn't among them

### MinaPlay Version

v0.2.1

### Problem Positioning

web ui

### Problem Description

There is an issue with the frontend internationalization (i18n) implementation. When the browser language is set to a language other than Chinese(zh_CN) or English(en_US), the UI fails to display the fonts correctly. Please investigate and fix the issue to ensure proper font display for all browser languages.
![1](https://github.com/nepsyn/minaplay/assets/45781074/9f7686c3-942c-4924-b733-7d60aba60b7c)

**Comment by nepsyn** [comment]
Will fix in the next version(0.2.2)
